{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-ntier-platform.fullname" . }}-backend
  labels:
    app: backend
    {{- include "secure-ntier-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: backend
        {{- include "secure-ntier-platform.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ include "secure-ntier-platform.image" (dict "repository" .Values.backend.image.repository "tag" .Values.backend.image.tag "Chart" .Chart "Values" .Values) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "secure-ntier-platform.fullname" . }}-config
          env:
            - name: DB_HOST
              value: {{ required "backend.env.DB_HOST is required (RDS/Flexible Server/Cloud SQL endpoint)" .Values.backend.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.backend.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.env.DB_NAME | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end }}
