{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secure-ntier-platform.fullname" . }}-backend
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
---
{{- if and .Values.frontend.enabled .Values.frontend.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "secure-ntier-platform.fullname" . }}-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
